Add ml_processing attribute to nucliadb_writer models
nuclia/nucliadb pull request #140
Opened 2022-06-20 17:13 UTC by albertnadal

### Description
Add the new 'ml_processing' attribute to nucliadb_writer models, CreateResourcePayload and PushPayload.

### How was this PR tested?
Describe how you tested this PR.

2022-06-20 17:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuclia/nucliadb?pullRequest=140) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuclia/nucliadb?pullRequest=140) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuclia/nucliadb?pullRequest=140) it.</sub>

2022-06-20 17:48 UTC, bloodbare requested changes
defining a list of disabled features will have more extensibility that just a bool parameter

2022-06-21 09:29 UTC, albertnadal commented
Replaced the 'ml_processing' bool attribute for a the nested 'PushProcessingOptions' model that works as a place for defining processing options (with default values).

2022-06-21 15:31 UTC, bloodbare approved these changes

2022-06-21 15:58 UTC, merged