Set zone on sentry as tag
nuclia/nucliadb pull request #1527
Opened 2023-11-01 16:03 UTC by sunbit

2023-11-01 16:26 UTC, vangheem requested changes

2023-11-01 16:26 UTC, vangheem commented on charts/nucliadb/values.yaml
> +  NUCLIA_ZONE: "provider-region-ordinal"
Can we keep the default here?

2023-11-02 08:38 UTC, sunbit commented on charts/nucliadb/values.yaml
> +  NUCLIA_ZONE: "provider-region-ordinal"
done

2023-11-02 17:56 UTC, vangheem approved these changes

2023-11-15 13:44 UTC, merged