remove vectorset from index
nuclia/nucliadb pull request #2047
Opened 2024-04-08 11:25 UTC by hermeGarcia

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2024-04-08 12:40 UTC, javitonino requested changes

2024-04-08 12:40 UTC, javitonino commented on nucliadb_vectors/src/service/writer.rs
> -        debug!("{id:?} - Main index set resource: ends {v} ms");
Keep this?

2024-04-08 12:40 UTC, javitonino commented on nucliadb_vectors/src/service/writer.rs
> -        debug!("{id:?} - Ending at {took} ms");
Keep this!

2024-04-10 13:37 UTC, lferran commented
[sc-9600] [sc-9614]

2024-04-10 13:42 UTC, merged