Max tokens for LLM
nuclia/nucliadb pull request #2065
Opened 2024-04-15 15:56 UTC by lferran

### Description
Adds a way for the API users to limit the amount of AI tokens used for the LLM context and the LLM answer.

### How was this PR tested?
Integration tests

2024-04-15 15:57 UTC, lferran commented
[sc-9732]

2024-04-15 16:03 UTC, vangheem requested changes

2024-04-15 16:03 UTC, vangheem commented on nucliadb_models/nucliadb_models/search.py
> +    max_tokens: Optional[MaxTokens] = Field(
Is this a breaking change to the API?

2024-04-16 07:57 UTC, lferran commented on nucliadb_models/nucliadb_models/search.py
> +    max_tokens: Optional[MaxTokens] = Field(
changed

2024-04-17 13:36 UTC, vangheem approved these changes

2024-04-17 13:44 UTC, merged