Sc 1793  nucliadb metrics bytes fields and searches
nuclia/nucliadb pull request #232
Opened 2022-08-30 17:35 UTC by sunbit

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2022-09-02 07:05 UTC, bloodbare requested changes

2022-09-02 07:05 UTC, bloodbare commented on nucliadb_ingest/nucliadb_ingest/orm/processor.py
> +            storage = await get_storage()
Why we remove service_name ?

2022-09-02 07:05 UTC, bloodbare commented on nucliadb_ingest/nucliadb_ingest/tests/fixtures.py
> +    set_utility(Utility.PUBSUB, pubsub)
Could we check if already exist ?

2022-09-02 07:05 UTC, bloodbare commented on nucliadb_utils/nucliadb_utils/storages/gcs.py
> +                assert data["resource"]["name"] == destination_uri
Are you sure?

2022-09-02 08:15 UTC, sunbit commented on nucliadb_ingest/nucliadb_ingest/fields/base.py
> +        async for key in self.resource.txn.keys(field_base_key):
I'll check, but the first result of the `.keys` includes the provided key, so a single key`.keys` call will emit the same key.

2022-09-02 09:03 UTC, bloodbare commented on nucliadb_ingest/nucliadb_ingest/fields/base.py
> +        async for key in self.resource.txn.keys(field_base_key):
just make sure it works with the three drivers

2022-09-05 13:35 UTC, bloodbare approved these changes

2022-09-05 13:37 UTC, merged