send bytes estimated kb_usage
nuclia/nucliadb pull request #2379
Opened 2024-08-07 10:57 UTC by drf7

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2024-08-07 12:23 UTC, sunbit requested changes

2024-08-07 12:23 UTC, sunbit commented on nucliadb/src/nucliadb/ingest/consumer/auditing.py
> +            * 10000
use the `AVG_PARAGRAPH_SIZE_BYTES`  on `nucliadb/src/nucliadb/search/api/v1/knowledgebox.py` to keep this consistent with what nucliadb outputs of current size

2024-08-07 13:43 UTC, lferran approved these changes

2024-08-08 08:09 UTC, sunbit approved these changes

2024-08-08 08:40 UTC, merged