Add script to recompute vectors of a KB
nuclia/nucliadb pull request #329
Opened 2022-10-26 12:15 UTC by lferran

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2022-11-03 12:02 UTC, jotare requested changes

2022-11-03 12:02 UTC, jotare commented on nucliadb_client/nucliadb_client/resource.py
> +        response = self.http_reader_v1.get("?", params=params, timeout=timeout).content
Is `?` needed when passing `params`?

2022-11-03 12:02 UTC, jotare commented on nucliadb_client/nucliadb_client/resource.py
> +        response = self.http_reader_v1.get("").content
What's the point to get the resource on `update` function?

2022-11-07 08:54 UTC, lferran commented on nucliadb_client/examples/kb_admin.py
> +DEFAULT_TRAIN_GRPC_PORT = 8080
train doesn't expose a HTTP service right now. It only exposes the grpc servicer, which happens to serve at port 8080

2022-11-08 13:13 UTC, jotare approved these changes

2022-11-08 13:15 UTC, jotare commented on nucliadb_client/examples/fix-prod-index-data.py
> +    # )
To delete?

2022-11-08 14:06 UTC, merged