Fix pubsub errors
nuclia/nucliadb pull request #336
Opened 2022-10-31 12:43 UTC by lferran

### Description
If there were more than one request active for resources of the same KB, we would get a KeyError trying to unsubscribe the pubsub handler.

### How was this PR tested?
Adding a unit test

2022-10-31 14:01 UTC, lferran commented on nucliadb/nucliadb/writer/api/v1/upload.py
> -    logger.info(request.headers)
I have deleted this after seeing some bearer tokens being logged in the terminal.

Please let me know if it has any use and needs to be put back

2022-11-02 09:01 UTC, jotare requested changes

2022-11-02 09:02 UTC, lferran commented on nucliadb_utils/nucliadb_utils/cache/redis.py
>          await self.pubsub.unsubscribe(key)
not needed, this subscription_id trick is only needed for the nats driver.

The redis client handles this well

2022-11-02 09:41 UTC, jotare approved these changes

2022-11-02 09:44 UTC, merged