Ensure all writer endpoints set info on span
nuclia/nucliadb pull request #359
Opened 2022-11-10 11:42 UTC by jotare

2022-11-10 11:55 UTC, bloodbare requested changes
needs to be conditional that tracer provider exist

2022-11-10 11:56 UTC, jotare commented on nucliadb/nucliadb/writer/api/v1/upload.py
> +    if rid:
But only if `rslug` is passed. You can call the endpoint only passing `upload_id`

2022-11-10 12:02 UTC, lferran commented on nucliadb/nucliadb/writer/api/v1/upload.py
> +    if rid:
ah totally right!

2022-11-10 12:12 UTC, bloodbare approved these changes
rereviewed

2022-11-11 10:31 UTC, bloodbare approved these changes

2022-11-11 14:27 UTC, merged