Add telemetry to client's writer stub
nuclia/nucliadb pull request #468
Opened 2022-12-28 12:30 UTC by lferran

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2022-12-28 12:54 UTC, bloodbare requested changes
You need to have nucliadb_telemetry also as a requirements.txt dependency for external download

2022-12-28 13:28 UTC, lferran commented
cc: @albertnadal you will have to pick up the latest version on your code once this PR is merged

2022-12-28 14:14 UTC, bloodbare approved these changes

2022-12-28 14:32 UTC, albertnadal approved these changes

2022-12-28 18:38 UTC, merged

2022-12-30 11:24 UTC, lferran commented
[sc-3373]