Protos implementations
nuclia/nucliadb pull request #535
Opened 2023-01-26 12:06 UTC by bloodbare

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

2023-01-26 13:24 UTC, vangheem approved these changes

2023-01-27 09:08 UTC, jotare requested changes

2023-01-27 09:08 UTC, jotare commented on nucliadb_vectors/src/relations/service/tests.rs
> +        metadata: None,
I miss some test checking metadata is correctly stored and retrieved

2023-01-27 09:34 UTC, jotare approved these changes

2023-01-27 10:16 UTC, merged