Persist and expose node metadata
nuclia/nucliadb pull request #620
Opened 2023-02-24 16:48 UTC by alekece

### Description
This PR aims to introduce node metadata with persistence and retrievable through gRPC method on the node writer itself.

### How was this PR tested?
Tested locally.

2023-03-08 16:24 UTC, hermeGarcia requested changes

2023-03-13 08:31 UTC, alekece commented on nucliadb_node/src/node_metadata.rs
> +
Nice catch

2023-03-13 08:32 UTC, alekece commented on nucliadb_node/src/node_metadata.rs
> +    }
Ditto

2023-03-13 16:27 UTC, hermeGarcia approved these changes

2023-03-14 09:03 UTC, merged