Replace chitchat monitor for an HTTP connection
nuclia/nucliadb pull request #865
Opened 2023-04-28 07:27 UTC by lferran

### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Integration, unit and local tests

2023-05-03 10:16 UTC, lferran commented
[ch-5320]

2023-05-05 10:31 UTC, hermeGarcia approved these changes
LGTM

2023-05-05 10:39 UTC, vangheem requested changes

2023-05-05 10:39 UTC, vangheem commented on .github/workflows/nucliadb_one.yml
> +        # TODO: un-comment when we sort out image cache issues
Just remove this now. We don't need the commented code as we have other examples on how to set it up. Also can you fix the 2 above this?

2023-05-05 11:14 UTC, vangheem approved these changes

2023-05-05 11:15 UTC, merged